version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://hex_machina:password@postgres:5432/hex_machina
      - DATABASE_URL_SYNC=postgresql://hex_machina:password@postgres:5432/hex_machina
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=true
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - hex-machina-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hex_machina
      POSTGRES_USER: hex_machina
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hex-machina-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hex-machina-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hexmachina.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - hex-machina-network

volumes:
  postgres_data:
  redis_data:

networks:
  hex-machina-network:
    driver: bridge 