name: ArticleIsCompleteTask
description: "Task to check if an article is complete"
steps:
  - name: fetch_articles
    runnable: ArticleFetcher
    config:
      db_path: "storage/articles14.db"
      filters:
        limit: 5
    dataset: false

  - name: prompt_template
    runnable: PromptTemplate
    config:
      prompt_name: "article_completeness"
    dataset: false

  - name: llm_processor
    runnable: ChatOpenAI
    config:
      model: "google/gemini-2.5-flash"
      temperature: 0.0
      max_tokens: 4000
      base_url: "https://openrouter.ai/api/v1"
      api_key: "${OPENROUTER_API_KEY}"
    dataset: false

metadata:
  category: "article_is_complete"
  tags:
    - "article_is_complete"
