# Enhanced Scrapy Configuration for Hex Machina v2
# This configuration demonstrates all available Scrapy settings for optimal ingestion

db_path: "storage/articles.db"
articles_limit: 10  # Limit articles per scraper
date_threshold: "2024-07-20"  # Only articles after this date
log_level: "INFO"

scrapy:
  # Basic Settings - Stealth Focused
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  robotstxt_obey: false
  
  # Performance Settings - Conservative for Stealth
  concurrent_requests: 4  # Much lower for stealth
  concurrent_requests_per_domain: 2  # Very conservative per domain
  concurrent_requests_per_ip: 1  # Limit per IP for stealth
  
  # Download Settings - Human-like Behavior
  download_delay: 3.0  # Longer delays for stealth
  download_timeout: 120  # Reasonable timeout
  download_maxsize: 10485760  # 10MB limit to prevent large downloads
  
      # Retry Settings - Handle temporary failures and redirects
    retry_enabled: true
    retry_times: 3
    retry_http_codes: [500, 502, 503, 504, 408, 301, 302, 307, 308]  # Include redirect codes
  
  # Cache Settings - Reduce load on target sites and improve performance
  httpcache_enabled: true
  httpcache_expiration_secs: 3600  # Cache for 1 hour
  httpcache_dir: ".scrapy/httpcache"
  
  # Cookie Settings - Maintain session state
  cookies_enabled: true
  
  # Compression Settings - Standard
  compression_enabled: true
  
  # AutoThrottle Settings - Automatically adjust request rate
  autothrottle_enabled: true
  autothrottle_start_delay: 2.0  # Longer initial delay
  autothrottle_max_delay: 30.0  # Shorter max delay
  autothrottle_target_concurrency: 0.5  # Very low target concurrency
  
  # Memory Settings - Monitor and limit memory usage
  memusage_enabled: true
  memusage_limit: 536870912  # 512MB limit
  
  # Logging Settings
  log_enabled: true
  log_stdout: true
  
  # Stats Settings - Collect performance statistics
  stats_enabled: true
  
  # Telnet Settings - Disabled for Security
  telnet_console_enabled: false
  
  # Custom Settings - Additional Scrapy settings
  custom_settings:
    # Additional settings that don't have direct config fields
    DOWNLOAD_FAIL_ON_DATALOSS: false
    DOWNLOAD_WARNSIZE: 5242880  # 5MB warning
    DOWNLOAD_MAXSIZE: 10485760  # 10MB max
    REACTOR_THREADPOOL_MAXSIZE: 10  # Smaller thread pool
    
    # Cookie and Session Settings
    COOKIES_DEBUG: false
    COOKIES_ENABLED: true
    
    # Redirect Settings - Handle 301/302 redirects properly
    REDIRECT_ENABLED: true
    REDIRECT_MAX_TIMES: 10  # Allow more redirects for complex sites
    REDIRECT_PRIORITY_ADJUST: 0  # Don't change priority for redirects
    
    # Crawl Settings - Conservative
    AJAXCRAWL_ENABLED: false
    DEPTH_LIMIT: 1  # Limit depth for RSS feeds
    DEPTH_PRIORITY: 0
    
    # DNS Settings - Conservative
    DNSCACHE_ENABLED: true
    DNSCACHE_SIZE: 1000  # Smaller cache
    DNS_TIMEOUT: 30  # Shorter timeout
    
    # Additional Stealth Settings
    DOWNLOADER_MIDDLEWARES: {
      'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': None,
      'scrapy.downloadermiddlewares.retry.RetryMiddleware': 550,
      'src.hex_machina.ingestion.middleware.CustomRedirectMiddleware': 600,  # Custom redirect handling
      'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 750,
      'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810,
      'scrapy.downloadermiddlewares.cookies.CookiesMiddleware': 700,
      'scrapy.downloadermiddlewares.httpcache.HttpCacheMiddleware': 900,
      'src.hex_machina.ingestion.middleware.RedirectLoggingMiddleware': 950,  # Log redirects
    }
    
    # Disable default user agent middleware to use custom one
    DOWNLOADER_MIDDLEWARES: {
      'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware': None,
    }
    
    # Request Fingerprinting Protection
    DOWNLOAD_DELAY: 3.0
    RANDOMIZE_DOWNLOAD_DELAY: 0.5  # Add randomization
    
    # Headers for Stealth
    DEFAULT_REQUEST_HEADERS: {
      'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
      'Accept-Language': 'en-US,en;q=0.5',
      'Accept-Encoding': 'gzip, deflate',
      'Connection': 'keep-alive',
      'Upgrade-Insecure-Requests': '1',
    }

scrapers:
  - scraper_0:
    type: playwright_rss_article_scraper
    start_urls:
      - "https://www.aws.amazon.com/rss"

  - scraper_1:
    type: stealth_playwright_rss_article_scraper
    start_urls:
      - "https://www.kdnuggets.com/feed"
      - "https://www.techcrunch.com/feed"
    browser_type: "chromium"
    headless: true  # Stealth mode makes headless less detectable
    launch_args:
      - "--disable-blink-features=AutomationControlled"
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-gpu"
      - "--disable-web-security"
      - "--disable-features=VizDisplayCompositor"
      - "--disable-extensions"
      - "--disable-plugins"
      - "--disable-images"  # Reduce bandwidth and detection
      - "--disable-javascript"  # For RSS feeds, JS not needed
      - "--disable-background-timer-throttling"
      - "--disable-backgrounding-occluded-windows"
      - "--disable-renderer-backgrounding"
      - "--disable-field-trial-config"
      - "--disable-ipc-flooding-protection"
      - "--no-first-run"
      - "--no-default-browser-check"
      - "--disable-default-apps"
      - "--disable-sync"
      - "--disable-translate"
      - "--hide-scrollbars"
      - "--mute-audio"
      - "--no-zygote"
      - "--disable-logging"
      - "--disable-background-networking"
      - "--disable-background-timer-throttling"
      - "--disable-client-side-phishing-detection"
      - "--disable-component-extensions-with-background-pages"
      - "--disable-default-apps"
      - "--disable-domain-reliability"
      - "--disable-features=TranslateUI"
      - "--disable-ipc-flooding-protection"
      - "--no-first-run"
      - "--no-default-browser-check"
      - "--disable-default-apps"
      - "--disable-sync"
      - "--disable-translate"
      - "--hide-scrollbars"
      - "--mute-audio"
      - "--no-zygote"
      - "--disable-logging"
      - "--disable-background-networking"
      - "--disable-background-timer-throttling"
      - "--disable-client-side-phishing-detection"
      - "--disable-component-extensions-with-background-pages"
      - "--disable-default-apps"
      - "--disable-domain-reliability"
      - "--disable-features=TranslateUI"
      - "--disable-ipc-flooding-protection"
    max_retries: 3
    screenshot_on_error: false