# Scraping Configuration for Hex Machina v2
# This file configures different scraper types and their RSS feeds

# Global scraping settings
global:
  articles_limit: 2  # Maximum articles to process per run
  date_threshold: "2024-01-01"  # Only process articles newer than this date
  db_path: 'data/hex_machina.db'
  #timeout: 30  # Timeout for page loading in seconds

# RSS Feed configurations by scraper type
rss_feeds:

  playwright:
    - name: "AWS Blog"
      url: "https://www.aws.amazon.com/rss"

  #stealth_playwright:
  #  - name: "AWS Blog"
  #    url: "https://www.kdnuggets.com/feed"
  #  - name: "OpenAI Blog"
  #    url: "https://www.techcrunch.com/feed"
  #    enabled: false

# Scraper-specific settings
scrapers:
  playwright_rss_article_scraper:
    enabled: true

  stealth_playwright_rss_article_scraper:
    browser_type: "chromium"
    headless: true  # Stealth mode makes headless less detectable
    launch_args:
      - "--disable-blink-features=AutomationControlled"
      - "--no-sandbox"
    wait_until: "networkidle"
    viewport:
      width: 1920
      height: 1080
    user_agent: null
    java_script_enabled: true
    ignore_https_errors: true
    screenshot_on_error: true
    extra_http_headers: {}
    enable_stealth: true
    stealth_options: {}

scrapy:
  download_delay: 2
  concurrent_requests: 4
  concurrent_requests_per_domain: 2
  user_agent: "  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  robots_txt_obey: false
  log_level: "DEBUG"
  retry_enabled: true
  retry_times: 3
  cookies_enabled: false