annotation_session:
  name: "article_completeness_annotation"
  description: "Annotate article completeness examples with quality and relevance scores"
  
  dataset:
    name: "ArticleIsCompleteTask_article_completeness_20250815_163024"
    split: "small" #"uncomplete_example"
  
  display_fields:
    inputs:
      - "title"
      - "url"
      - "text_content"
    outputs:
      - "['generations'][0][0]['text']['is_complete']"
  
  annotation_fields:
    outputs:
      - name: "['generations'][0][0]['text']['is_complete']"
        field_type: "replace"
        options: "boolean"
      - name: "['generations'][0][0]['text']['reasons']"
        field_type: "replace"
        options: "free_text"
